import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import profilePic from "../../public/images/profile/profile-pic-1.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icon'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
/* eslint-disable */

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
      <title>Toan's Portfolio | Home Page</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full rounded-[2rem]'>
              <Image 
                src={profilePic} 
                alt="CodeBucks" 
                className="w-90% h-auto rounded-2xl lg:hidden md:inline-block md:w-full" 
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className='w-1/2 flex flex-col ml-10 items-center self-center lg:w-full lg:text-center' >
              <AnimatedText text="Wedding & Events Coordinator" className='!text-6xl !text-left 
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
              Với vai trò là một Wedding & Events Coordinator, tôi luôn sẵn sàng lắng nghe vấn đề từ Khách hàng, đội ngũ trong team  để tìm kiếm, gợi ý
               giải pháp. 
               <br />
              Xem thêm các thông tin cá nhân và dự án đã thực hiện để hiểu rõ tôi hơn nha
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/LeVanToan-CV-Event.pdf" target={"_blank"}
                className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base'
                download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link href="mailto:lvtoan.cv@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light
                md:text-base'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
      
        <div className='absolute right-8 bottom-8 inline-block w-24 '>
          <Image src={lightBulb} alt='CodeBucks' className='w-full h-auto md:hidden' />
        </div>
      </main>
    </>
  )
}
